INSERT INTO POST (id, slug, author, title, perex, body, published)
VALUES (1, 'post-01-886dd30f', 'Petr Kovář', 'Článek č. 1: Technologie', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labo', '<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor inci<p>Další obsah článku s více detaily a odstavci.</p>', '2025-12-16'),
(2, 'post-02-fe32355b', 'Marie Dvořáková', 'Článek č. 2: Cestování', '<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pari', '<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu <p>Další obsah článku s více detaily a odstavci.</p>', '2025-01-27'),
(3, 'post-03-87875476', 'Petr Kovář', 'Článek č. 3: Technologie', '<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo ', '<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor i<p>Další obsah článku s více detaily a odstavci.</p>', '2025-06-07'),
(4, 'post-04-cc229181', 'Eva Svobodová', 'Článek č. 4: Kuchařka', '<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pari', '<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p><p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea<p>Další obsah článku s více detaily a odstavci.</p>', NULL),
(5, 'post-05-78febcdb', 'Eva Svobodová', 'Článek č. 5: Sport', '<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pari', '<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor i<p>Další obsah článku s více detaily a odstavci.</p>', '2025-11-29'),
(6, 'post-06-611b2cb8', 'Tomáš Svoboda', 'Článek č. 6: Cestování', '<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo ', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui o<p>Další obsah článku s více detaily a odstavci.</p>', '2025-05-13'),
(7, 'post-07-57f751ff', 'Eva Svobodová', 'Článek č. 7: Kuchařka', '<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pari', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiu<p>Další obsah článku s více detaily a odstavci.</p>', '2025-04-22'),
(8, 'post-08-8e6d60fa', 'Petr Kovář', 'Článek č. 8: Cestování', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labo', '<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt molli<p>Další obsah článku s více detaily a odstavci.</p>', NULL),
(9, 'post-09-8eb96138', 'Eva Svobodová', 'Článek č. 9: Zdraví', '<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui o<p>Další obsah článku s více detaily a odstavci.</p>', '2025-04-24'),
(10, 'post-10-faa982cb', 'Jan Novák', 'Článek č. 10: Kuchařka', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labo', '<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deseru<p>Další obsah článku s více detaily a odstavci.</p>', '2025-01-27');
